name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Build
        run: ./gradlew :build --stacktrace

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: JW3bGnLO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 409222
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: build/libs/!(*-@(dev|sources)).jar
          name: 0.4.0 for MC 1.17+
          version: 0.4.0+1.17-1.21
          version-type: release
          loaders: |
            fabric
          game-versions: |
            1.17
            1.17.1
            1.18
            1.18.1
            1.18.2
            1.19
            1.19.1
            1.19.2
            1.19.3
            1.19.4
            1.20
            1.20.1
            1.20.2
            1.20.3
            1.20.4
            1.20.5
            1.20.6
            1.21
          dependencies: |
            cloth-config  | depends
            modmenu       | recommends
